import os

Import('env')

source_files = ['waveform.cpp', 'wavetable.cpp', 'phasor.cpp']#, 'function.cpp', 'grain.cpp', 'slot.cpp']

grain_lib = env.Library('grain', source_files)

Return('grain_lib')
