import os

Import('env')

source_files = ['waveform.cpp', 'phasor.cpp',  'grain.cpp', 'graingenerator.cpp']  # 'slot.cpp', 'function.cpp']

grain_lib = env.Library('grain', source_files)

Return('grain_lib')
